# api-gateway/main.py
from contextlib import asynccontextmanager
import asyncio
import hashlib
import json
import os
import time

import httpx
from fastapi import FastAPI, HTTPException, Request
from prometheus_fastapi_instrumentator import Instrumentator
import redis

VLLM_URL = os.environ.get("VLLM_URL", "").rstrip("/")
QDRANT_URL = os.environ.get("QDRANT_URL", "http://qdrant:6333").rstrip("/")
REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379")
MODEL_NAME = os.environ.get("MODEL_NAME", "Qwen/Qwen2.5-7B-Instruct-GPTQ-Int4")
REMOTE_HEADERS = {"ngrok-skip-browser-warning": "true"}

SAMPLE_DOCS = [
    {
        "id": "doc_001",
        "text": "Platform engineering standardizes developer workflows with shared infrastructure, automation, and observability.",
        "timestamp": 0,
    },
    {
        "id": "doc_002",
        "text": "A hybrid AI platform can run orchestration and monitoring locally while serving GPU models remotely.",
        "timestamp": 0,
    },
]


def deterministic_embedding(text: str, size: int = 384) -> list[float]:
    """Small local embedding substitute for offline smoke tests."""
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    return [((digest[i % len(digest)] / 255.0) * 2) - 1 for i in range(size)]


async def ensure_qdrant_collection(client: httpx.AsyncClient) -> None:
    collection_url = f"{QDRANT_URL}/collections/documents"
    exists = await client.get(collection_url)
    if exists.status_code == 404:
        await client.put(
            collection_url,
            json={"vectors": {"size": 384, "distance": "Cosine"}},
        )
    elif exists.status_code >= 400:
        exists.raise_for_status()


async def seed_demo_data() -> None:
    last_error = None
    for _ in range(12):
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                await ensure_qdrant_collection(client)
                points = [
                    {
                        "id": idx + 1,
                        "vector": deterministic_embedding(doc["text"]),
                        "payload": doc,
                    }
                    for idx, doc in enumerate(SAMPLE_DOCS)
                ]
                await client.put(
                    f"{QDRANT_URL}/collections/documents/points",
                    json={"points": points},
                )

            store = redis.from_url(REDIS_URL, decode_responses=True)
            for doc in SAMPLE_DOCS:
                store.set(
                    f"feature:{doc['id']}",
                    json.dumps({"text": doc["text"], "timestamp": doc["timestamp"], "processed": True}),
                )
            return
        except Exception as exc:
            last_error = exc
            await asyncio.sleep(2)
    raise RuntimeError(f"Could not seed demo data: {last_error}")


@asynccontextmanager
async def lifespan(app: FastAPI):
    try:
        await seed_demo_data()
    except Exception as exc:
        print(f"Startup seed skipped: {exc}")
    yield


app = FastAPI(title="AI Platform API Gateway", lifespan=lifespan)
Instrumentator().instrument(app).expose(app)


def fallback_answer(query: str, context: list[dict]) -> dict:
    snippets = []
    for item in context:
        payload = item.get("payload", {}) if isinstance(item, dict) else {}
        if payload.get("text"):
            snippets.append(payload["text"])
    evidence = " ".join(snippets) or "The local demo knowledge base is available."
    return {
        "answer": (
            f"Platform answer for '{query}': {evidence} "
            "This response is generated by the local fallback because no remote vLLM URL is configured."
        ),
        "model": "local-fallback",
    }


@app.post("/api/v1/chat")
async def chat(request: Request):
    body = await request.json()
    query = body.get("query")
    if not query:
        raise HTTPException(status_code=422, detail="Field 'query' is required")

    embedding = body.get("embedding") or deterministic_embedding(query)
    if not isinstance(embedding, list) or len(embedding) != 384:
        raise HTTPException(status_code=422, detail="Field 'embedding' must be a 384-dimension vector")

    start = time.time()

    async with httpx.AsyncClient(timeout=10) as client:
        await ensure_qdrant_collection(client)
        search_resp = await client.post(
            f"{QDRANT_URL}/collections/documents/points/search",
            json={"vector": embedding, "limit": 3},
        )
        context = search_resp.json().get("result", []) if search_resp.status_code < 400 else []

    prompt = f"Context: {context}\n\nQuery: {query}"
    result = fallback_answer(query, context)
    if VLLM_URL:
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                llm_resp = await client.post(
                    f"{VLLM_URL}/v1/chat/completions",
                    headers=REMOTE_HEADERS,
                    json={
                        "model": MODEL_NAME,
                        "messages": [{"role": "user", "content": prompt}],
                    },
                )
                llm_resp.raise_for_status()
                data = llm_resp.json()
                result = {
                    "answer": data["choices"][0]["message"]["content"],
                    "model": data.get("model", MODEL_NAME),
                }
        except Exception as exc:
            result["warning"] = f"Remote vLLM unavailable, used local fallback: {exc}"

    latency = (time.time() - start) * 1000
    return {
        "answer": result["answer"],
        "latency_ms": round(latency, 2),
        "model": result["model"],
        **({"warning": result["warning"]} if "warning" in result else {}),
    }


@app.get("/health")
def health():
    return {
        "status": "ok",
        "vllm_configured": bool(VLLM_URL),
        "qdrant_url": QDRANT_URL,
    }
